---
title: "Practical Machine Learning Course Project"
author: "Wei Liew"
date: "4/14/2022"
output: 
  html_document: 
    keep_md: yes
keep_md: true
---

# Background and Overview 
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively.  These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks.  One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it.  

In this project, we aim to use data from accelerometers on the belt, forearm, arm, and dumbbell of 6 participants, to predict the manner in which they did the exercise, which is represented in the “classe” variable in the training set.  They were asked to perform barbell lifts correctly and incorrectly in 5 different ways, which corresponds from Class A to Class E as below: 
•	Class A - exactly according to the specification 
•	Class B - throwing the elbows to the front
•	Class C - lifting the dumbbell only halfway
•	Class D - lowering the dumbbell only halfway
•	Class E - throwing the hips to the front  
Only Class A is the correct performance, and the other 4 classes correspond to other common mistakes. 
More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

This report will address how the model was built, how cross validation was used, what the expected out-of-sample is, and why the choices were made.  Finally the prediction model will be used to predict 20 test cases. 

# Data Processing and Visualization
We started by loading the necessary libraries and dataset, followed by downloading the raw data and providing some basic data visualization.  

```r
knitr::opts_chunk$set(echo = TRUE)
# Loading necessary libraries
library(caret)
```

```
## Warning: package 'caret' was built under R version 4.1.1
```

```
## Loading required package: lattice
```

```
## Loading required package: ggplot2
```

```r
library(rattle)
```

```
## Warning: package 'rattle' was built under R version 4.1.1
```

```
## Loading required package: tibble
```

```
## Loading required package: bitops
```

```
## Rattle: A free graphical interface for data science with R.
## Version 5.4.0 Copyright (c) 2006-2020 Togaware Pty Ltd.
## Type 'rattle()' to shake, rattle, and roll your data.
```

```r
library(ggplot2)
```

```r
# Download the raw data file (training and testing data sets) from provided URLs
if(!file.exists("./data")) dir.create("./data")
trainUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testUrl <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
if (!file.exists("./data/pml-training.csv")) 
{ download.file(trainUrl, destfile="./data/pml-training.csv")}
if (!file.exists("./data/pml-testing.csv")) 
{ download.file(testUrl, destfile="./data/pml-testing.csv")}

# Load data into R by reading the generated csv file.
traincsv <- read.csv("./data/pml-training.csv")
testcsv <- read.csv("./data/pml-testing.csv")
```


```r
dim(traincsv)
```

```
## [1] 19622   160
```

```r
dim(testcsv)
```

```
## [1]  20 160
```

```r
sum(is.na(traincsv))
```

```
## [1] 1287472
```

```r
sum(is.na(testcsv))
```

```
## [1] 2000
```

```r
names(traincsv)[names(traincsv) != names(testcsv)]
```

```
## [1] "classe"
```

```r
names(testcsv)[names(traincsv) != names(testcsv)]
```

```
## [1] "problem_id"
```

There are 19622 observations and 160 variables in the training data, while the testing data contains 20 observations and the same variables as the training set.  The outcome of this giving classification problem is determined to be the variable ‘classe’ in the last column in the training set.  However, the outcome variable ‘classe’ does not exist in the testing set, instead represented by another variable ‘problem_id’ as identification purposes of the 20 test cases for the submission of the prediction results.
  
There is a considerable number of NA or missing values.  Columns (predictors) that do not produce any information, such as NA values, will be removed to easier the analysis process.  


```r
training <- traincsv[, colSums(is.na(traincsv)) == 0]
testing <- testcsv[, colSums(is.na(testcsv)) == 0]
dim(training)
```

```
## [1] 19622    93
```

```r
dim(testing)
```

```
## [1] 20 60
```
We will continue to remove the first seven predictors (such as X, user name, timestamps) since these variables do not make intuitive sense for prediction and believe to have little impact for the outcome classe.  We will also get rid of near zero variance predictors (zero covariates) as these variables are not useful when constructing a prediction model.


```r
trainingA <- training[, -c(1:7)]
testingA <- testing[, -c(1:7)]
dim(trainingA)
```

```
## [1] 19622    86
```

```r
dim(testingA)
```

```
## [1] 20 53
```

```r
#Remove near zero variance variables
nzv <- nearZeroVar(trainingA)
trainData <- trainingA[,-nzv]
dim(trainData)
```

```
## [1] 19622    53
```

```r
nvzTest <- nearZeroVar(testingA)
nvzTest
```

```
## integer(0)
```

```r
testData <- testingA
dim(testData)
```

```
## [1] 20 53
```

After the data cleaning process above, the number of variables (predictors) has been reduced to 53 from 160.  No near zero covariate for the testing data has been found.  It is shown that our training data have the same column numbers (predictors) as the testing data has for the prediction model.

# Prediction Model Building and Selection
To practice cross validation, the given training data is partitioned into 70% training and 30% testing (validation).  The original testing data (testData) will stay as is and will be used later for the final prediction of the 20 different test cases.


```r
set.seed(12345)
inTrain <- createDataPartition(trainData$classe, p = 0.7, list = FALSE)
train <- trainData[inTrain,]
valid <- trainData[-inTrain,]
dim(train)
```

```
## [1] 13737    53
```

```r
dim(valid)
```

```
## [1] 5885   53
```
This project is a supervised machine learning problem since we clearly know our project objective and the categorical outcome variable, classe which takes values in a finite, unordered set.  Therefore, we will use supervised classification algorithms for the model prediction.  We will build and consider three different popular models, i.e. Decision Tree, Random Forests, and Gradient Boosted Tree on the training data (sub-training set).  Confusion Matrix will be performed to compare the different models by evaluating the accuracy of models on new data (sub-test set).  The prediction model with the highest accuracy will be selected to use on the untouched independent original testing set (testData) to fulfill the cross validation to predict the 20 different test cases, thus the result will be on an unbiased measurement of the out of sample accuracy of the model.

###TrainControl
We can specify the type of resampling or set options for how the model will be applied to the training data by creating the trainControl object below.  We use the cross validation method to avoid overfitting effects, to better estimate test error and for better model overall efficiency.  5-fold cross validation is considered when implementing the algorithms to save some computing time.


```r
fitControl <- trainControl(method="cv", number=5)
```

##Decision Tree Model


```r
#Train the model
rpartFit <- train(classe~., data= train, method="rpart", trControl=fitControl, tuneLength = 5)
rpartFit
```

```
## CART 
## 
## 13737 samples
##    52 predictor
##     5 classes: 'A', 'B', 'C', 'D', 'E' 
## 
## No pre-processing
## Resampling: Cross-Validated (5 fold) 
## Summary of sample sizes: 10987, 10990, 10990, 10991, 10990 
## Resampling results across tuning parameters:
## 
##   cp          Accuracy   Kappa     
##   0.02166616  0.5574059  0.43113696
##   0.02797274  0.5406635  0.40938336
##   0.03458448  0.5269759  0.39101780
##   0.06092971  0.3911382  0.16699598
##   0.11595972  0.3326679  0.07359069
## 
## Accuracy was used to select the optimal model using the largest value.
## The final value used for the model was cp = 0.02166616.
```

```r
#Prettier version of plot 
fancyRpartPlot(rpartFit$finalModel, cex = 0.7, tweak = 0.7)
```

```
## Warning: cex and tweak both specified, applying both
```

![](PML-course-proj_files/figure-html/decisiontreemodel-1.png)<!-- -->

```r
#Predicting classe for validation set (valid) using classification tree model  
pred_rpart <- predict(rpartFit, newdata = valid)

#Compare and print results of models 
cm_rpart <- confusionMatrix(factor(valid$classe), pred_rpart)
cm_rpart
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1525   29   77   39    4
##          B  484  351  124  180    0
##          C  499   36  423   68    0
##          D  423    9  126  406    0
##          E  153  138  143  167  481
## 
## Overall Statistics
##                                           
##                Accuracy : 0.5414          
##                  95% CI : (0.5285, 0.5542)
##     No Information Rate : 0.524           
##     P-Value [Acc > NIR] : 0.004016        
##                                           
##                   Kappa : 0.402           
##                                           
##  Mcnemar's Test P-Value : < 2.2e-16       
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.4945  0.62345  0.47368  0.47209  0.99175
## Specificity            0.9468  0.85194  0.87921  0.88896  0.88870
## Pos Pred Value         0.9110  0.30817  0.41228  0.42116  0.44455
## Neg Pred Value         0.6298  0.95533  0.90327  0.90774  0.99917
## Prevalence             0.5240  0.09567  0.15174  0.14613  0.08241
## Detection Rate         0.2591  0.05964  0.07188  0.06899  0.08173
## Detection Prevalence   0.2845  0.19354  0.17434  0.16381  0.18386
## Balanced Accuracy      0.7206  0.73769  0.67645  0.68052  0.94023
```
The accuracy has been found to be 0.5414 (55.14%), which is considerable low and the expected out of sample error rate is estimated to be around 44.86%, which is very high. 

##Random Forests Model

```r
#Train the model
rfModFit <- train(classe~., data= train, method = "rf", trControl=fitControl, tuneLength = 5)
rfModFit
```

```
## Random Forest 
## 
## 13737 samples
##    52 predictor
##     5 classes: 'A', 'B', 'C', 'D', 'E' 
## 
## No pre-processing
## Resampling: Cross-Validated (5 fold) 
## Summary of sample sizes: 10990, 10989, 10990, 10990, 10989 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy   Kappa    
##    2    0.9903908  0.9878442
##   14    0.9926474  0.9906990
##   27    0.9900269  0.9873836
##   39    0.9882071  0.9850815
##   52    0.9831843  0.9787271
## 
## Accuracy was used to select the optimal model using the largest value.
## The final value used for the model was mtry = 14.
```

```r
#Predicting classe for validation set (valid) using random forests model  
predRF <- predict(rfModFit, newdata = valid)

#Compare and print results of models 
cmRF <- confusionMatrix(factor(valid$classe), predRF)
cmRF
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1673    1    0    0    0
##          B    4 1134    1    0    0
##          C    0    5 1020    1    0
##          D    0    0    9  954    1
##          E    0    0    1    1 1080
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9959          
##                  95% CI : (0.9939, 0.9974)
##     No Information Rate : 0.285           
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9948          
##                                           
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9976   0.9947   0.9893   0.9979   0.9991
## Specificity            0.9998   0.9989   0.9988   0.9980   0.9996
## Pos Pred Value         0.9994   0.9956   0.9942   0.9896   0.9982
## Neg Pred Value         0.9991   0.9987   0.9977   0.9996   0.9998
## Prevalence             0.2850   0.1937   0.1752   0.1624   0.1837
## Detection Rate         0.2843   0.1927   0.1733   0.1621   0.1835
## Detection Prevalence   0.2845   0.1935   0.1743   0.1638   0.1839
## Balanced Accuracy      0.9987   0.9968   0.9940   0.9979   0.9993
```

The accuracy has been found to be 0.9948 (99.48%), which is considerable high and the expected out of sample error rate is estimated to be around 0.52%, which is very low. 

Below are the two reference plots for the random forests model.

```r
p1 <- plot(rfModFit, main="Accuracy of Random Forest Model by number of predictors")
p1
```

![](PML-course-proj_files/figure-html/accuracy_noofpreditorsplot-1.png)<!-- -->


```r
p2 <- plot(rfModFit$finalModel, main = "Model Error of Random Forest model by number of trees")
```

![](PML-course-proj_files/figure-html/error_nooftreesplot-1.png)<!-- -->

```r
p2
```

```
##                OOB           A           B           C           D           E
##   [1,] 0.076154307 0.043293116 0.116207951 0.097560976 0.077575758 0.060948081
##   [2,] 0.082946494 0.040869565 0.134207241 0.113168724 0.078549849 0.067243675
##   [3,] 0.079283140 0.043940954 0.119284294 0.102153506 0.090303030 0.059542796
##   [4,] 0.072875195 0.037827944 0.106364041 0.089965398 0.088794926 0.061021760
##   [5,] 0.069171717 0.035277383 0.102032352 0.090194265 0.080867850 0.056219566
##   [6,] 0.061151637 0.027056573 0.087043722 0.085625555 0.070688030 0.054707379
##   [7,] 0.054246534 0.022890604 0.079389910 0.071614583 0.066820276 0.048527582
##   [8,] 0.049832152 0.020680628 0.072776280 0.066809422 0.062784349 0.043177189
##   [9,] 0.046279156 0.020291363 0.071892925 0.059023355 0.053297200 0.041178845
##  [10,] 0.040633051 0.015794925 0.061193463 0.054476351 0.055206463 0.031250000
##  [11,] 0.037153745 0.012896570 0.057910674 0.051658967 0.049597855 0.027910686
##  [12,] 0.032746144 0.014138817 0.049452624 0.041893590 0.046854083 0.022673031
##  [13,] 0.029845301 0.012060559 0.046757164 0.034323985 0.043613707 0.023025010
##  [14,] 0.026250547 0.010002565 0.045231813 0.031746032 0.035142349 0.018253968
##  [15,] 0.025287859 0.009741092 0.042561205 0.032567850 0.033792797 0.016653450
##  [16,] 0.023382867 0.008198821 0.040286145 0.030467446 0.033333333 0.013476021
##  [17,] 0.021555491 0.007172131 0.037246050 0.026711185 0.030653043 0.014268728
##  [18,] 0.019804864 0.006656426 0.034612491 0.024624374 0.029764549 0.011097899
##  [19,] 0.018784128 0.005888377 0.031602709 0.025876461 0.027543314 0.010697306
##  [20,] 0.016672734 0.005376344 0.028969150 0.022120200 0.023989338 0.009508716
##  [21,] 0.016453116 0.005376344 0.028969150 0.020868114 0.023545091 0.009900990
##  [22,] 0.014486424 0.004352279 0.023702032 0.019198664 0.022646536 0.008712871
##  [23,] 0.014413627 0.003584229 0.025959368 0.017946578 0.021758437 0.009108911
##  [24,] 0.013758463 0.003328213 0.023702032 0.020033389 0.019982238 0.007920792
##  [25,] 0.012884909 0.003328213 0.023325809 0.016277129 0.019094139 0.007920792
##  [26,] 0.012739317 0.002816180 0.023325809 0.017111853 0.018206039 0.007920792
##  [27,] 0.012302541 0.003072197 0.021444695 0.017111853 0.018206039 0.007128713
##  [28,] 0.012520929 0.003328213 0.023702032 0.015442404 0.018650089 0.006732673
##  [29,] 0.011720172 0.003328213 0.021820918 0.014607679 0.018206039 0.005544554
##  [30,] 0.011501784 0.002816180 0.019939804 0.015859766 0.018650089 0.005544554
##  [31,] 0.011137803 0.003072197 0.018811136 0.016277129 0.017317940 0.005148515
##  [32,] 0.011283395 0.002816180 0.021444695 0.015025042 0.017761989 0.004356436
##  [33,] 0.010919415 0.003072197 0.018058691 0.014607679 0.018650089 0.005148515
##  [34,] 0.010846619 0.002816180 0.018811136 0.015442404 0.016429840 0.005544554
##  [35,] 0.010773823 0.002304147 0.019939804 0.015859766 0.015097691 0.005544554
##  [36,] 0.010701026 0.002816180 0.020692250 0.015442404 0.015541741 0.003564356
##  [37,] 0.010264250 0.002816180 0.016930023 0.015025042 0.017317940 0.003960396
##  [38,] 0.010118658 0.002816180 0.016553800 0.014607679 0.016429840 0.004752475
##  [39,] 0.010482638 0.002560164 0.016930023 0.014190317 0.019094139 0.004752475
##  [40,] 0.010409842 0.002816180 0.016553800 0.015859766 0.017317940 0.004356436
##  [41,] 0.009681881 0.002816180 0.015425132 0.014190317 0.016873890 0.003564356
##  [42,] 0.009390697 0.002816180 0.015801354 0.012520868 0.016873890 0.003168317
##  [43,] 0.008808328 0.002560164 0.013544018 0.014190317 0.014653641 0.003168317
##  [44,] 0.008881124 0.002816180 0.014296464 0.012520868 0.015097691 0.003564356
##  [45,] 0.008808328 0.002304147 0.013544018 0.012938230 0.015097691 0.004356436
##  [46,] 0.008953920 0.002304147 0.013544018 0.012938230 0.015541741 0.004752475
##  [47,] 0.008371551 0.002048131 0.012791573 0.011268781 0.015985790 0.003960396
##  [48,] 0.008589940 0.002304147 0.011662904 0.012103506 0.016429840 0.004752475
##  [49,] 0.008517143 0.002304147 0.012791573 0.012103506 0.015097691 0.004356436
##  [50,] 0.008953920 0.002560164 0.014296464 0.012103506 0.015541741 0.004356436
##  [51,] 0.008881124 0.002560164 0.013920241 0.012103506 0.015541741 0.004356436
##  [52,] 0.008735532 0.002304147 0.014672686 0.011268781 0.015097691 0.004356436
##  [53,] 0.008735532 0.002304147 0.014296464 0.012103506 0.015097691 0.003960396
##  [54,] 0.008808328 0.002304147 0.013920241 0.012938230 0.015097691 0.003960396
##  [55,] 0.008589940 0.002304147 0.013167795 0.013355593 0.015097691 0.003168317
##  [56,] 0.008444347 0.002304147 0.012415350 0.012938230 0.014653641 0.003960396
##  [57,] 0.008517143 0.002048131 0.012791573 0.012938230 0.015097691 0.003960396
##  [58,] 0.008298755 0.002048131 0.012791573 0.012520868 0.014209591 0.003960396
##  [59,] 0.008080367 0.002048131 0.012039127 0.012103506 0.014653641 0.003564356
##  [60,] 0.008225959 0.002048131 0.012415350 0.012938230 0.013765542 0.003960396
##  [61,] 0.007934775 0.002048131 0.011662904 0.012520868 0.013321492 0.003960396
##  [62,] 0.007789182 0.001536098 0.011662904 0.012520868 0.014209591 0.003168317
##  [63,] 0.007934775 0.001536098 0.011286682 0.013355593 0.013765542 0.003960396
##  [64,] 0.008007571 0.001536098 0.010910459 0.013355593 0.014653641 0.003960396
##  [65,] 0.007789182 0.001536098 0.010534236 0.013772955 0.014209591 0.003168317
##  [66,] 0.007789182 0.001536098 0.010534236 0.013772955 0.014209591 0.003168317
##  [67,] 0.007934775 0.001536098 0.011662904 0.013355593 0.013765542 0.003564356
##  [68,] 0.007861979 0.001536098 0.012039127 0.012938230 0.013765542 0.003168317
##  [69,] 0.007716386 0.001536098 0.010910459 0.012520868 0.014209591 0.003564356
##  [70,] 0.007643590 0.001536098 0.011286682 0.012520868 0.013765542 0.003168317
##  [71,] 0.007643590 0.001536098 0.010910459 0.012520868 0.013321492 0.003960396
##  [72,] 0.007789182 0.001536098 0.011286682 0.012938230 0.013321492 0.003960396
##  [73,] 0.007425202 0.001536098 0.010910459 0.011268781 0.013765542 0.003564356
##  [74,] 0.007497998 0.001536098 0.010910459 0.012103506 0.013321492 0.003564356
##  [75,] 0.007352406 0.001536098 0.010910459 0.011268781 0.013321492 0.003564356
##  [76,] 0.007279610 0.001536098 0.010534236 0.011268781 0.012877442 0.003960396
##  [77,] 0.007206814 0.001536098 0.010534236 0.011686144 0.012433393 0.003564356
##  [78,] 0.007425202 0.001536098 0.010910459 0.011268781 0.013765542 0.003564356
##  [79,] 0.007206814 0.001536098 0.010158014 0.011686144 0.012877442 0.003564356
##  [80,] 0.006988425 0.001536098 0.009781791 0.011268781 0.012877442 0.003168317
##  [81,] 0.007061222 0.001536098 0.010158014 0.010434057 0.012877442 0.003960396
##  [82,] 0.007352406 0.001536098 0.010910459 0.010851419 0.013321492 0.003960396
##  [83,] 0.007061222 0.001536098 0.010158014 0.010434057 0.012877442 0.003960396
##  [84,] 0.007134018 0.001536098 0.010534236 0.010434057 0.012877442 0.003960396
##  [85,] 0.006988425 0.001536098 0.010534236 0.010016694 0.012877442 0.003564356
##  [86,] 0.006842833 0.001536098 0.010910459 0.010016694 0.011989343 0.003168317
##  [87,] 0.007206814 0.001536098 0.010910459 0.010016694 0.013321492 0.003960396
##  [88,] 0.006697241 0.001536098 0.010534236 0.009181970 0.012433393 0.003168317
##  [89,] 0.006915629 0.001536098 0.010910459 0.009599332 0.012433393 0.003564356
##  [90,] 0.006915629 0.001536098 0.010910459 0.010016694 0.011989343 0.003564356
##  [91,] 0.006697241 0.001536098 0.010910459 0.009181970 0.011989343 0.003168317
##  [92,] 0.006551649 0.001536098 0.010158014 0.009599332 0.011545293 0.003168317
##  [93,] 0.006915629 0.001536098 0.010910459 0.010434057 0.011989343 0.003168317
##  [94,] 0.006478853 0.001536098 0.010158014 0.010016694 0.011101243 0.002772277
##  [95,] 0.006624445 0.001536098 0.010158014 0.010434057 0.011101243 0.003168317
##  [96,] 0.006624445 0.001536098 0.010158014 0.010434057 0.011101243 0.003168317
##  [97,] 0.006624445 0.001536098 0.009781791 0.010851419 0.011101243 0.003168317
##  [98,] 0.006478853 0.001536098 0.009781791 0.010434057 0.010657194 0.003168317
##  [99,] 0.006478853 0.001536098 0.009405568 0.010851419 0.010657194 0.003168317
## [100,] 0.006624445 0.001536098 0.009781791 0.010851419 0.010213144 0.003960396
## [101,] 0.006624445 0.001536098 0.009781791 0.010434057 0.011101243 0.003564356
## [102,] 0.006551649 0.001536098 0.009781791 0.010434057 0.010657194 0.003564356
## [103,] 0.006624445 0.001536098 0.009781791 0.010434057 0.011101243 0.003564356
## [104,] 0.006478853 0.001536098 0.009029345 0.010016694 0.011101243 0.003960396
## [105,] 0.006770037 0.001536098 0.009781791 0.010851419 0.011545293 0.003564356
## [106,] 0.006551649 0.001536098 0.009029345 0.010434057 0.011101243 0.003960396
## [107,] 0.006697241 0.001536098 0.009405568 0.010434057 0.011545293 0.003960396
## [108,] 0.006478853 0.001536098 0.009405568 0.009599332 0.011101243 0.003960396
## [109,] 0.006478853 0.001536098 0.009029345 0.010016694 0.011101243 0.003960396
## [110,] 0.006260464 0.001536098 0.009029345 0.010016694 0.010657194 0.003168317
## [111,] 0.006187668 0.001536098 0.008653123 0.009181970 0.011101243 0.003564356
## [112,] 0.006260464 0.001536098 0.009029345 0.009599332 0.011101243 0.003168317
## [113,] 0.006042076 0.001536098 0.008653123 0.008764608 0.011101243 0.003168317
## [114,] 0.006333261 0.001536098 0.009029345 0.010016694 0.010657194 0.003564356
## [115,] 0.006406057 0.001536098 0.009029345 0.010016694 0.010657194 0.003960396
## [116,] 0.006260464 0.001536098 0.008276900 0.009599332 0.011101243 0.003960396
## [117,] 0.006042076 0.001792115 0.008653123 0.008764608 0.010213144 0.003564356
## [118,] 0.006042076 0.001536098 0.008276900 0.009599332 0.010213144 0.003564356
## [119,] 0.006187668 0.001536098 0.008653123 0.009599332 0.010213144 0.003960396
## [120,] 0.006042076 0.001536098 0.008276900 0.009181970 0.010213144 0.003960396
## [121,] 0.006187668 0.001536098 0.008276900 0.009181970 0.010657194 0.004356436
## [122,] 0.006333261 0.001536098 0.008653123 0.010016694 0.010213144 0.004356436
## [123,] 0.006551649 0.001792115 0.008653123 0.010434057 0.010657194 0.004356436
## [124,] 0.006406057 0.001792115 0.008653123 0.010016694 0.010213144 0.004356436
## [125,] 0.006478853 0.001792115 0.008653123 0.010016694 0.010657194 0.004356436
## [126,] 0.006333261 0.001792115 0.008653123 0.009181970 0.010657194 0.004356436
## [127,] 0.006406057 0.001792115 0.008653123 0.010016694 0.010213144 0.004356436
## [128,] 0.006478853 0.002048131 0.008653123 0.010016694 0.010657194 0.003960396
## [129,] 0.006478853 0.002048131 0.008276900 0.010016694 0.011101243 0.003960396
## [130,] 0.006406057 0.002048131 0.008276900 0.009181970 0.011101243 0.004356436
## [131,] 0.006478853 0.002048131 0.008653123 0.009599332 0.011101243 0.003960396
## [132,] 0.006406057 0.002048131 0.008653123 0.009181970 0.011101243 0.003960396
## [133,] 0.006478853 0.002048131 0.008653123 0.010016694 0.011101243 0.003564356
## [134,] 0.006551649 0.002048131 0.009029345 0.010016694 0.011101243 0.003564356
## [135,] 0.006406057 0.002048131 0.009405568 0.009181970 0.010657194 0.003564356
## [136,] 0.006551649 0.002048131 0.009405568 0.010016694 0.010657194 0.003564356
## [137,] 0.006478853 0.002048131 0.009029345 0.010016694 0.010657194 0.003564356
## [138,] 0.006260464 0.001792115 0.008653123 0.009599332 0.010657194 0.003564356
## [139,] 0.006260464 0.001536098 0.009029345 0.009599332 0.010657194 0.003564356
## [140,] 0.006333261 0.001792115 0.008653123 0.009181970 0.011545293 0.003564356
## [141,] 0.006551649 0.001792115 0.008653123 0.010851419 0.010657194 0.003960396
## [142,] 0.006187668 0.001536098 0.008653123 0.009599332 0.010657194 0.003564356
## [143,] 0.006333261 0.001536098 0.007900677 0.010851419 0.011101243 0.003564356
## [144,] 0.006406057 0.001536098 0.008653123 0.010016694 0.011545293 0.003564356
## [145,] 0.006478853 0.001792115 0.009029345 0.010016694 0.011101243 0.003564356
## [146,] 0.006551649 0.001792115 0.009029345 0.010434057 0.011101243 0.003564356
## [147,] 0.006478853 0.001536098 0.009405568 0.010016694 0.011101243 0.003564356
## [148,] 0.006260464 0.001792115 0.008653123 0.009181970 0.011101243 0.003564356
## [149,] 0.006478853 0.001792115 0.009029345 0.009599332 0.011101243 0.003960396
## [150,] 0.006551649 0.002048131 0.008653123 0.010016694 0.011101243 0.003960396
## [151,] 0.006260464 0.002048131 0.008653123 0.009599332 0.010213144 0.003564356
## [152,] 0.006333261 0.001792115 0.008276900 0.010016694 0.010657194 0.003960396
## [153,] 0.006333261 0.002048131 0.008276900 0.009599332 0.010657194 0.003960396
## [154,] 0.006406057 0.002048131 0.008276900 0.010016694 0.010657194 0.003960396
## [155,] 0.006260464 0.002048131 0.007900677 0.010016694 0.010213144 0.003960396
## [156,] 0.006260464 0.002048131 0.008276900 0.009599332 0.010213144 0.003960396
## [157,] 0.006114872 0.002048131 0.008276900 0.009181970 0.010213144 0.003564356
## [158,] 0.006187668 0.002048131 0.008653123 0.009181970 0.010213144 0.003564356
## [159,] 0.006260464 0.002048131 0.009029345 0.009181970 0.010213144 0.003564356
## [160,] 0.006333261 0.002048131 0.009029345 0.009181970 0.010213144 0.003960396
## [161,] 0.006260464 0.002048131 0.008653123 0.009181970 0.010213144 0.003960396
## [162,] 0.006187668 0.002048131 0.008276900 0.009181970 0.010213144 0.003960396
## [163,] 0.006042076 0.002048131 0.007900677 0.009181970 0.009769094 0.003960396
## [164,] 0.006042076 0.002048131 0.008276900 0.009181970 0.009769094 0.003564356
## [165,] 0.006042076 0.002048131 0.008276900 0.009181970 0.009769094 0.003564356
## [166,] 0.005969280 0.001792115 0.008276900 0.009181970 0.009769094 0.003564356
## [167,] 0.006114872 0.001792115 0.008653123 0.009181970 0.009769094 0.003960396
## [168,] 0.006042076 0.001792115 0.008276900 0.009181970 0.009769094 0.003960396
## [169,] 0.005896484 0.001792115 0.008276900 0.008764608 0.009769094 0.003564356
## [170,] 0.006042076 0.001792115 0.007900677 0.009181970 0.010213144 0.003960396
## [171,] 0.006042076 0.001792115 0.008276900 0.009181970 0.009769094 0.003960396
## [172,] 0.005969280 0.001792115 0.007900677 0.009181970 0.010213144 0.003564356
## [173,] 0.006042076 0.001792115 0.008276900 0.009181970 0.010213144 0.003564356
## [174,] 0.006042076 0.001792115 0.007900677 0.009181970 0.010213144 0.003960396
## [175,] 0.005969280 0.001536098 0.008276900 0.009181970 0.009769094 0.003960396
## [176,] 0.005896484 0.001792115 0.007524454 0.009181970 0.009769094 0.003960396
## [177,] 0.005896484 0.001536098 0.007900677 0.009181970 0.009769094 0.003960396
## [178,] 0.005823688 0.001280082 0.008276900 0.008764608 0.010213144 0.003564356
## [179,] 0.005969280 0.001536098 0.007900677 0.009181970 0.010213144 0.003960396
## [180,] 0.005896484 0.001280082 0.007900677 0.008764608 0.010213144 0.004356436
## [181,] 0.005969280 0.001536098 0.007900677 0.009181970 0.010213144 0.003960396
## [182,] 0.005896484 0.001536098 0.007900677 0.008764608 0.009769094 0.004356436
## [183,] 0.005823688 0.001536098 0.007900677 0.008347245 0.009769094 0.004356436
## [184,] 0.005896484 0.001536098 0.007900677 0.008764608 0.009769094 0.004356436
## [185,] 0.005896484 0.001536098 0.007900677 0.008764608 0.009769094 0.004356436
## [186,] 0.005896484 0.001536098 0.007900677 0.008764608 0.009769094 0.004356436
## [187,] 0.005969280 0.001792115 0.007900677 0.008764608 0.009769094 0.004356436
## [188,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009769094 0.003960396
## [189,] 0.005750892 0.001536098 0.007900677 0.008764608 0.009769094 0.003564356
## [190,] 0.005896484 0.001792115 0.007900677 0.008764608 0.009769094 0.003960396
## [191,] 0.005896484 0.001536098 0.007900677 0.009181970 0.009769094 0.003960396
## [192,] 0.005896484 0.001536098 0.007900677 0.008764608 0.009769094 0.004356436
## [193,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009769094 0.003960396
## [194,] 0.005969280 0.001536098 0.007900677 0.009599332 0.009769094 0.003960396
## [195,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009769094 0.003960396
## [196,] 0.005896484 0.001536098 0.007900677 0.009599332 0.009769094 0.003564356
## [197,] 0.005896484 0.001536098 0.007900677 0.009181970 0.009769094 0.003960396
## [198,] 0.005969280 0.001536098 0.007900677 0.009599332 0.009769094 0.003960396
## [199,] 0.005750892 0.001536098 0.007900677 0.008347245 0.009769094 0.003960396
## [200,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009769094 0.003960396
## [201,] 0.005969280 0.001536098 0.007900677 0.009181970 0.009769094 0.004356436
## [202,] 0.006042076 0.001536098 0.008276900 0.009599332 0.009769094 0.003960396
## [203,] 0.005969280 0.001536098 0.008276900 0.009181970 0.009769094 0.003960396
## [204,] 0.005969280 0.001536098 0.008276900 0.009181970 0.009769094 0.003960396
## [205,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009769094 0.003960396
## [206,] 0.005969280 0.001536098 0.008276900 0.009181970 0.009769094 0.003960396
## [207,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009769094 0.003960396
## [208,] 0.005750892 0.001536098 0.008276900 0.008764608 0.009769094 0.003168317
## [209,] 0.005969280 0.001536098 0.008276900 0.008764608 0.009769094 0.004356436
## [210,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009325044 0.004356436
## [211,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009769094 0.003960396
## [212,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [213,] 0.005823688 0.001536098 0.007900677 0.008764608 0.009325044 0.004356436
## [214,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [215,] 0.005750892 0.001536098 0.007900677 0.008764608 0.009325044 0.003960396
## [216,] 0.005823688 0.001280082 0.007900677 0.008764608 0.009769094 0.004356436
## [217,] 0.005678096 0.001536098 0.007900677 0.008764608 0.009325044 0.003564356
## [218,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009769094 0.003960396
## [219,] 0.005823688 0.001536098 0.008276900 0.008764608 0.009769094 0.003564356
## [220,] 0.005896484 0.001536098 0.008653123 0.008764608 0.009325044 0.003960396
## [221,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [222,] 0.005823688 0.001536098 0.008276900 0.008764608 0.009769094 0.003564356
## [223,] 0.005823688 0.001536098 0.008276900 0.008764608 0.009769094 0.003564356
## [224,] 0.005823688 0.001536098 0.008276900 0.008347245 0.009769094 0.003960396
## [225,] 0.005823688 0.001536098 0.008276900 0.008347245 0.009769094 0.003960396
## [226,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [227,] 0.005969280 0.001536098 0.008276900 0.008764608 0.009769094 0.004356436
## [228,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [229,] 0.005969280 0.001536098 0.008653123 0.008764608 0.009325044 0.004356436
## [230,] 0.005896484 0.001536098 0.008653123 0.008764608 0.009325044 0.003960396
## [231,] 0.005969280 0.001536098 0.008653123 0.008764608 0.009325044 0.004356436
## [232,] 0.005969280 0.001536098 0.008653123 0.008764608 0.009325044 0.004356436
## [233,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [234,] 0.005896484 0.001536098 0.008276900 0.008764608 0.009325044 0.004356436
## [235,] 0.005750892 0.001536098 0.008276900 0.008347245 0.009325044 0.003960396
## [236,] 0.005823688 0.001536098 0.008653123 0.008347245 0.009325044 0.003960396
## [237,] 0.005823688 0.001536098 0.008653123 0.008347245 0.009325044 0.003960396
## [238,] 0.005823688 0.001536098 0.008276900 0.008347245 0.009325044 0.004356436
## [239,] 0.005678096 0.001536098 0.007900677 0.007929883 0.009325044 0.004356436
## [240,] 0.005678096 0.001536098 0.007900677 0.008347245 0.009325044 0.003960396
## [241,] 0.005678096 0.001536098 0.007900677 0.007929883 0.009325044 0.004356436
## [242,] 0.005678096 0.001536098 0.008653123 0.007512521 0.009325044 0.003960396
## [243,] 0.005678096 0.001536098 0.008276900 0.007512521 0.009325044 0.004356436
## [244,] 0.005605300 0.001536098 0.008276900 0.007512521 0.009325044 0.003960396
## [245,] 0.005750892 0.001792115 0.008276900 0.007512521 0.009325044 0.004356436
## [246,] 0.005750892 0.001792115 0.007900677 0.007929883 0.009325044 0.004356436
## [247,] 0.005678096 0.001536098 0.008276900 0.007929883 0.009325044 0.003960396
## [248,] 0.005678096 0.001536098 0.008276900 0.007512521 0.009325044 0.004356436
## [249,] 0.005678096 0.001536098 0.008276900 0.007512521 0.009325044 0.004356436
## [250,] 0.005605300 0.001536098 0.007900677 0.007512521 0.009325044 0.004356436
## [251,] 0.005605300 0.001536098 0.007900677 0.007512521 0.009325044 0.004356436
## [252,] 0.005605300 0.001536098 0.007900677 0.007929883 0.009325044 0.003960396
## [253,] 0.005678096 0.001536098 0.008276900 0.007929883 0.009325044 0.003960396
## [254,] 0.005678096 0.001536098 0.008276900 0.007929883 0.009325044 0.003960396
## [255,] 0.005605300 0.001536098 0.007900677 0.007929883 0.009325044 0.003960396
## [256,] 0.005678096 0.001536098 0.007900677 0.007929883 0.009325044 0.004356436
## [257,] 0.005678096 0.001536098 0.007900677 0.008347245 0.009325044 0.003960396
## [258,] 0.005823688 0.001536098 0.007900677 0.008347245 0.009769094 0.004356436
## [259,] 0.005750892 0.001536098 0.007900677 0.008347245 0.009325044 0.004356436
## [260,] 0.005750892 0.001536098 0.008276900 0.008347245 0.009325044 0.003960396
## [261,] 0.005823688 0.001536098 0.008276900 0.008347245 0.009325044 0.004356436
## [262,] 0.005896484 0.001536098 0.008276900 0.008347245 0.009769094 0.004356436
## [263,] 0.005969280 0.001536098 0.009029345 0.008347245 0.009325044 0.004356436
## [264,] 0.005823688 0.001280082 0.008653123 0.008347245 0.009325044 0.004356436
## [265,] 0.005823688 0.001536098 0.008653123 0.008347245 0.009325044 0.003960396
## [266,] 0.005678096 0.001280082 0.008276900 0.007512521 0.009325044 0.004752475
## [267,] 0.005605300 0.001280082 0.007900677 0.007512521 0.009325044 0.004752475
## [268,] 0.005750892 0.001536098 0.008276900 0.007512521 0.009325044 0.004752475
## [269,] 0.005896484 0.001536098 0.008653123 0.007929883 0.009325044 0.004752475
## [270,] 0.005823688 0.001280082 0.008276900 0.007929883 0.009769094 0.004752475
## [271,] 0.005896484 0.001280082 0.008653123 0.007929883 0.009769094 0.004752475
## [272,] 0.005823688 0.001536098 0.008276900 0.007929883 0.009769094 0.004356436
## [273,] 0.005896484 0.001536098 0.008276900 0.007929883 0.009769094 0.004752475
## [274,] 0.005896484 0.001536098 0.008276900 0.007929883 0.009769094 0.004752475
## [275,] 0.006187668 0.001792115 0.009029345 0.007929883 0.010213144 0.004752475
## [276,] 0.006042076 0.001792115 0.009029345 0.007512521 0.009769094 0.004752475
## [277,] 0.005896484 0.001536098 0.008653123 0.007929883 0.009325044 0.004752475
## [278,] 0.005896484 0.001792115 0.008653123 0.007929883 0.009325044 0.004356436
## [279,] 0.005750892 0.001280082 0.008653123 0.007929883 0.009325044 0.004356436
## [280,] 0.006042076 0.001536098 0.008653123 0.008764608 0.009325044 0.004752475
## [281,] 0.005969280 0.001536098 0.008653123 0.008764608 0.009325044 0.004356436
## [282,] 0.005896484 0.001536098 0.008653123 0.008347245 0.009325044 0.004356436
## [283,] 0.005823688 0.001536098 0.007900677 0.007929883 0.009769094 0.004752475
## [284,] 0.005896484 0.001536098 0.007900677 0.008347245 0.009325044 0.005148515
## [285,] 0.005678096 0.001536098 0.007524454 0.007929883 0.009325044 0.004752475
## [286,] 0.005823688 0.001536098 0.007900677 0.008347245 0.009325044 0.004752475
## [287,] 0.005823688 0.001536098 0.007900677 0.007929883 0.009325044 0.005148515
## [288,] 0.005823688 0.001536098 0.007524454 0.007929883 0.009769094 0.005148515
## [289,] 0.005896484 0.001536098 0.007900677 0.008347245 0.009325044 0.005148515
## [290,] 0.006114872 0.001536098 0.008653123 0.008347245 0.009769094 0.005148515
## [291,] 0.006042076 0.001536098 0.008653123 0.008347245 0.009325044 0.005148515
## [292,] 0.005896484 0.001536098 0.007900677 0.008347245 0.009325044 0.005148515
## [293,] 0.005896484 0.001536098 0.008276900 0.008347245 0.009325044 0.004752475
## [294,] 0.006187668 0.001536098 0.008653123 0.008347245 0.009769094 0.005544554
## [295,] 0.006187668 0.001536098 0.008653123 0.008347245 0.009325044 0.005940594
## [296,] 0.006114872 0.001536098 0.008653123 0.008347245 0.009325044 0.005544554
## [297,] 0.006042076 0.001536098 0.008276900 0.008347245 0.009325044 0.005544554
## [298,] 0.005969280 0.001536098 0.008653123 0.008347245 0.009325044 0.004752475
## [299,] 0.006042076 0.001536098 0.008653123 0.008347245 0.009769094 0.004752475
## [300,] 0.005969280 0.001536098 0.008653123 0.007929883 0.009325044 0.005148515
## [301,] 0.005969280 0.001536098 0.008653123 0.007929883 0.009769094 0.004752475
## [302,] 0.006114872 0.001536098 0.008653123 0.008347245 0.009325044 0.005544554
## [303,] 0.006260464 0.001536098 0.009029345 0.008347245 0.009769094 0.005544554
## [304,] 0.005896484 0.001536098 0.008653123 0.008347245 0.008880995 0.004752475
## [305,] 0.006042076 0.001536098 0.008653123 0.008347245 0.008880995 0.005544554
## [306,] 0.005969280 0.001536098 0.008276900 0.008347245 0.008880995 0.005544554
## [307,] 0.005969280 0.001536098 0.007900677 0.008764608 0.008880995 0.005544554
## [308,] 0.005823688 0.001536098 0.007900677 0.008347245 0.008880995 0.005148515
## [309,] 0.005969280 0.001536098 0.007900677 0.008764608 0.008880995 0.005544554
## [310,] 0.005896484 0.001536098 0.007900677 0.009181970 0.008880995 0.004752475
## [311,] 0.005969280 0.001536098 0.007900677 0.009181970 0.008880995 0.005148515
## [312,] 0.005969280 0.001536098 0.007900677 0.009181970 0.008880995 0.005148515
## [313,] 0.005896484 0.001536098 0.007900677 0.008347245 0.008880995 0.005544554
## [314,] 0.005896484 0.001536098 0.007900677 0.008347245 0.008880995 0.005544554
## [315,] 0.005896484 0.001536098 0.007900677 0.008347245 0.008880995 0.005544554
## [316,] 0.005969280 0.001536098 0.007900677 0.008347245 0.009325044 0.005544554
## [317,] 0.005896484 0.001536098 0.007900677 0.008347245 0.008880995 0.005544554
## [318,] 0.005896484 0.001536098 0.007900677 0.008347245 0.008880995 0.005544554
## [319,] 0.006042076 0.001536098 0.008276900 0.008764608 0.008880995 0.005544554
## [320,] 0.006114872 0.001536098 0.008276900 0.008764608 0.009325044 0.005544554
## [321,] 0.006187668 0.001536098 0.008653123 0.008764608 0.008880995 0.005940594
## [322,] 0.006114872 0.001536098 0.008276900 0.009181970 0.008880995 0.005544554
## [323,] 0.006042076 0.001536098 0.007900677 0.008764608 0.008880995 0.005940594
## [324,] 0.005896484 0.001536098 0.007900677 0.008347245 0.008880995 0.005544554
## [325,] 0.005896484 0.001280082 0.007900677 0.008347245 0.008880995 0.005940594
## [326,] 0.005678096 0.001280082 0.007900677 0.008347245 0.008880995 0.004752475
## [327,] 0.005896484 0.001280082 0.007900677 0.008764608 0.008880995 0.005544554
## [328,] 0.005823688 0.001280082 0.007900677 0.008347245 0.009325044 0.005148515
## [329,] 0.005896484 0.001280082 0.007900677 0.008347245 0.009325044 0.005544554
## [330,] 0.005896484 0.001280082 0.008276900 0.008347245 0.009325044 0.005148515
## [331,] 0.005896484 0.001280082 0.007900677 0.008347245 0.009325044 0.005544554
## [332,] 0.005823688 0.001280082 0.007900677 0.008347245 0.009325044 0.005148515
## [333,] 0.005969280 0.001280082 0.007900677 0.008764608 0.009325044 0.005544554
## [334,] 0.005969280 0.001536098 0.007900677 0.008347245 0.009325044 0.005544554
## [335,] 0.005823688 0.001536098 0.008276900 0.008347245 0.009325044 0.004356436
## [336,] 0.005823688 0.001280082 0.008276900 0.008347245 0.009325044 0.004752475
## [337,] 0.005678096 0.001280082 0.007900677 0.008347245 0.009325044 0.004356436
## [338,] 0.005678096 0.001280082 0.007524454 0.008764608 0.009325044 0.004356436
## [339,] 0.005750892 0.001536098 0.007524454 0.008347245 0.009325044 0.004752475
## [340,] 0.005896484 0.001280082 0.007900677 0.009181970 0.009325044 0.004752475
## [341,] 0.005969280 0.001536098 0.007900677 0.009181970 0.009325044 0.004752475
## [342,] 0.005896484 0.001280082 0.008276900 0.009181970 0.009325044 0.004356436
## [343,] 0.005823688 0.001280082 0.008276900 0.008764608 0.009325044 0.004356436
## [344,] 0.005823688 0.001280082 0.008276900 0.009181970 0.009325044 0.003960396
## [345,] 0.005823688 0.001280082 0.008276900 0.009181970 0.009325044 0.003960396
## [346,] 0.005823688 0.001280082 0.007900677 0.009181970 0.009325044 0.004356436
## [347,] 0.005750892 0.001280082 0.007900677 0.009181970 0.009325044 0.003960396
## [348,] 0.005823688 0.001280082 0.007900677 0.009181970 0.009325044 0.004356436
## [349,] 0.005823688 0.001280082 0.007900677 0.008764608 0.009325044 0.004752475
## [350,] 0.005896484 0.001536098 0.007900677 0.009181970 0.009325044 0.004356436
## [351,] 0.005896484 0.001536098 0.007900677 0.008764608 0.009325044 0.004752475
## [352,] 0.005750892 0.001280082 0.007900677 0.008764608 0.009325044 0.004356436
## [353,] 0.005823688 0.001280082 0.007900677 0.009181970 0.009325044 0.004356436
## [354,] 0.005823688 0.001280082 0.007524454 0.008764608 0.009325044 0.005148515
## [355,] 0.006042076 0.001536098 0.007524454 0.009181970 0.009325044 0.005544554
## [356,] 0.005823688 0.001280082 0.007524454 0.009181970 0.009325044 0.004752475
## [357,] 0.005750892 0.001280082 0.007524454 0.008764608 0.009325044 0.004752475
## [358,] 0.005823688 0.001280082 0.007524454 0.009181970 0.008880995 0.005148515
## [359,] 0.005823688 0.001280082 0.007148232 0.009181970 0.009769094 0.004752475
## [360,] 0.005896484 0.001536098 0.007524454 0.009181970 0.009325044 0.004752475
## [361,] 0.005750892 0.001536098 0.007148232 0.008764608 0.009325044 0.004752475
## [362,] 0.005605300 0.001280082 0.007148232 0.009181970 0.008880995 0.004356436
## [363,] 0.005605300 0.001280082 0.007148232 0.009181970 0.008880995 0.004356436
## [364,] 0.005532503 0.001280082 0.007148232 0.008764608 0.008880995 0.004356436
## [365,] 0.005532503 0.001280082 0.007524454 0.008764608 0.008880995 0.003960396
## [366,] 0.005605300 0.001280082 0.007524454 0.008764608 0.009325044 0.003960396
## [367,] 0.005605300 0.001280082 0.007524454 0.008764608 0.009325044 0.003960396
## [368,] 0.005605300 0.001280082 0.007524454 0.008764608 0.009325044 0.003960396
## [369,] 0.005459707 0.001280082 0.007148232 0.008764608 0.008880995 0.003960396
## [370,] 0.005532503 0.001280082 0.007148232 0.008764608 0.009325044 0.003960396
## [371,] 0.005532503 0.001280082 0.007524454 0.008764608 0.008880995 0.003960396
## [372,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [373,] 0.005532503 0.001280082 0.007524454 0.008764608 0.009325044 0.003564356
## [374,] 0.005532503 0.001280082 0.007524454 0.008764608 0.009325044 0.003564356
## [375,] 0.005532503 0.001280082 0.007524454 0.008764608 0.009325044 0.003564356
## [376,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [377,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [378,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [379,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [380,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [381,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [382,] 0.005459707 0.001280082 0.007524454 0.008764608 0.009325044 0.003168317
## [383,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [384,] 0.005459707 0.001280082 0.007524454 0.008347245 0.009325044 0.003564356
## [385,] 0.005459707 0.001280082 0.007524454 0.008347245 0.009325044 0.003564356
## [386,] 0.005386911 0.001280082 0.007524454 0.008347245 0.009325044 0.003168317
## [387,] 0.005459707 0.001280082 0.007524454 0.008764608 0.009325044 0.003168317
## [388,] 0.005459707 0.001280082 0.007524454 0.008764608 0.009325044 0.003168317
## [389,] 0.005459707 0.001280082 0.007524454 0.008764608 0.009325044 0.003168317
## [390,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [391,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [392,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [393,] 0.005386911 0.001280082 0.007148232 0.008764608 0.008880995 0.003564356
## [394,] 0.005314115 0.001280082 0.006772009 0.008764608 0.008880995 0.003564356
## [395,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [396,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [397,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [398,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [399,] 0.005386911 0.001280082 0.007148232 0.008764608 0.009325044 0.003168317
## [400,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [401,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [402,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [403,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [404,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [405,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [406,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [407,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [408,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [409,] 0.005314115 0.001024066 0.007148232 0.008764608 0.009325044 0.003168317
## [410,] 0.005314115 0.001024066 0.007148232 0.008764608 0.009325044 0.003168317
## [411,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [412,] 0.005532503 0.001280082 0.007524454 0.008764608 0.009325044 0.003564356
## [413,] 0.005678096 0.001280082 0.007524454 0.008764608 0.009325044 0.004356436
## [414,] 0.005678096 0.001280082 0.007524454 0.008764608 0.009325044 0.004356436
## [415,] 0.005605300 0.001280082 0.007524454 0.008764608 0.009325044 0.003960396
## [416,] 0.005605300 0.001280082 0.007524454 0.008764608 0.008880995 0.004356436
## [417,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [418,] 0.005459707 0.001280082 0.007148232 0.008764608 0.008880995 0.003960396
## [419,] 0.005314115 0.001280082 0.006772009 0.008764608 0.008880995 0.003564356
## [420,] 0.005605300 0.001280082 0.007148232 0.009181970 0.008880995 0.004356436
## [421,] 0.005459707 0.001280082 0.007148232 0.008764608 0.008880995 0.003960396
## [422,] 0.005532503 0.001280082 0.007148232 0.008764608 0.008880995 0.004356436
## [423,] 0.005605300 0.001280082 0.007524454 0.008764608 0.008880995 0.004356436
## [424,] 0.005532503 0.001280082 0.007148232 0.008764608 0.008880995 0.004356436
## [425,] 0.005605300 0.001280082 0.007524454 0.008764608 0.008880995 0.004356436
## [426,] 0.005532503 0.001280082 0.007148232 0.008764608 0.008880995 0.004356436
## [427,] 0.005532503 0.001280082 0.006772009 0.009181970 0.008880995 0.004356436
## [428,] 0.005532503 0.001280082 0.007148232 0.009181970 0.008880995 0.003960396
## [429,] 0.005459707 0.001280082 0.006772009 0.008764608 0.008880995 0.004356436
## [430,] 0.005459707 0.001280082 0.006395786 0.008764608 0.009325044 0.004356436
## [431,] 0.005532503 0.001280082 0.006772009 0.008764608 0.009325044 0.004356436
## [432,] 0.005241319 0.001280082 0.006395786 0.008764608 0.008880995 0.003564356
## [433,] 0.005386911 0.001280082 0.006395786 0.008764608 0.009325044 0.003960396
## [434,] 0.005386911 0.001280082 0.006395786 0.008764608 0.009769094 0.003564356
## [435,] 0.005532503 0.001280082 0.006772009 0.008764608 0.009769094 0.003960396
## [436,] 0.005532503 0.001280082 0.006772009 0.008764608 0.009769094 0.003960396
## [437,] 0.005314115 0.001280082 0.006395786 0.008764608 0.008880995 0.003960396
## [438,] 0.005241319 0.001280082 0.006395786 0.008764608 0.008880995 0.003564356
## [439,] 0.005314115 0.001280082 0.006772009 0.008764608 0.008880995 0.003564356
## [440,] 0.005314115 0.001280082 0.006395786 0.008764608 0.009325044 0.003564356
## [441,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [442,] 0.005314115 0.001280082 0.006772009 0.008764608 0.008880995 0.003564356
## [443,] 0.005314115 0.001280082 0.006772009 0.008764608 0.008880995 0.003564356
## [444,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009769094 0.003168317
## [445,] 0.005459707 0.001280082 0.006772009 0.008764608 0.009769094 0.003564356
## [446,] 0.005459707 0.001280082 0.006772009 0.008764608 0.009769094 0.003564356
## [447,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [448,] 0.005459707 0.001280082 0.006772009 0.008764608 0.009769094 0.003564356
## [449,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [450,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [451,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [452,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [453,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [454,] 0.005459707 0.001280082 0.007148232 0.008764608 0.009325044 0.003564356
## [455,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [456,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [457,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [458,] 0.005314115 0.001280082 0.006395786 0.008764608 0.009325044 0.003564356
## [459,] 0.005314115 0.001280082 0.006395786 0.008764608 0.009325044 0.003564356
## [460,] 0.005241319 0.001280082 0.006395786 0.008764608 0.009325044 0.003168317
## [461,] 0.005314115 0.001024066 0.006395786 0.008764608 0.009769094 0.003564356
## [462,] 0.005168523 0.001024066 0.006395786 0.008764608 0.009325044 0.003168317
## [463,] 0.005241319 0.001024066 0.006395786 0.008764608 0.009769094 0.003168317
## [464,] 0.005386911 0.001024066 0.006772009 0.008764608 0.009769094 0.003564356
## [465,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [466,] 0.005386911 0.001280082 0.006772009 0.008764608 0.009325044 0.003564356
## [467,] 0.005459707 0.001280082 0.006772009 0.008764608 0.009769094 0.003564356
## [468,] 0.005314115 0.001280082 0.006395786 0.008764608 0.009325044 0.003564356
## [469,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [470,] 0.005241319 0.001024066 0.006772009 0.008764608 0.009325044 0.003168317
## [471,] 0.005241319 0.001024066 0.006772009 0.008764608 0.009325044 0.003168317
## [472,] 0.005314115 0.001280082 0.006772009 0.008764608 0.009325044 0.003168317
## [473,] 0.005314115 0.001024066 0.006772009 0.008764608 0.009769094 0.003168317
## [474,] 0.005314115 0.001024066 0.006772009 0.008764608 0.009769094 0.003168317
## [475,] 0.005386911 0.001024066 0.006772009 0.008764608 0.010213144 0.003168317
## [476,] 0.005314115 0.001024066 0.006772009 0.008764608 0.009769094 0.003168317
## [477,] 0.005459707 0.001280082 0.006772009 0.008764608 0.010213144 0.003168317
## [478,] 0.005314115 0.001024066 0.006772009 0.008764608 0.009769094 0.003168317
## [479,] 0.005241319 0.001024066 0.006395786 0.008764608 0.009769094 0.003168317
## [480,] 0.005314115 0.001024066 0.006395786 0.008764608 0.010213144 0.003168317
## [481,] 0.005241319 0.001024066 0.006395786 0.008347245 0.010213144 0.003168317
## [482,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [483,] 0.005314115 0.001024066 0.006395786 0.008764608 0.010213144 0.003168317
## [484,] 0.005241319 0.001024066 0.006019564 0.008764608 0.010213144 0.003168317
## [485,] 0.005241319 0.001024066 0.006395786 0.008347245 0.010213144 0.003168317
## [486,] 0.005241319 0.001024066 0.006395786 0.008347245 0.010213144 0.003168317
## [487,] 0.005314115 0.001024066 0.006395786 0.008764608 0.010213144 0.003168317
## [488,] 0.005241319 0.001024066 0.006019564 0.008764608 0.010213144 0.003168317
## [489,] 0.005241319 0.001024066 0.006019564 0.008764608 0.010213144 0.003168317
## [490,] 0.005241319 0.001024066 0.006019564 0.008764608 0.010213144 0.003168317
## [491,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [492,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [493,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [494,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [495,] 0.005241319 0.001024066 0.006019564 0.008764608 0.010213144 0.003168317
## [496,] 0.005241319 0.001024066 0.006019564 0.008764608 0.010213144 0.003168317
## [497,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [498,] 0.005241319 0.001024066 0.006019564 0.008347245 0.010213144 0.003564356
## [499,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
## [500,] 0.005168523 0.001024066 0.006019564 0.008347245 0.010213144 0.003168317
```

## Generalize Boosted Models

```r
gbmModFit <- train(classe~., data=train, method="gbm", trControl= fitControl, tuneLength = 5, verbose=FALSE)

#Predicting classe for validation set (valid) using generalized boosted model 
predGBM <- predict(gbmModFit, newdata = valid)

#Compare and print results of models 
cmGBM <- confusionMatrix(factor(valid$classe), predGBM)
cmGBM
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1671    3    0    0    0
##          B    6 1127    6    0    0
##          C    0   10 1014    2    0
##          D    0    0   13  951    0
##          E    0    2    1    2 1077
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9924          
##                  95% CI : (0.9898, 0.9944)
##     No Information Rate : 0.285           
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9903          
##                                           
##  Mcnemar's Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9964   0.9869   0.9807   0.9958   1.0000
## Specificity            0.9993   0.9975   0.9975   0.9974   0.9990
## Pos Pred Value         0.9982   0.9895   0.9883   0.9865   0.9954
## Neg Pred Value         0.9986   0.9968   0.9959   0.9992   1.0000
## Prevalence             0.2850   0.1941   0.1757   0.1623   0.1830
## Detection Rate         0.2839   0.1915   0.1723   0.1616   0.1830
## Detection Prevalence   0.2845   0.1935   0.1743   0.1638   0.1839
## Balanced Accuracy      0.9979   0.9922   0.9891   0.9966   0.9995
```

### Summarized Accuracy and Out of Sample Error

```r
AccuracyResults <- data.frame("Model" = c("Tree(rpart)", "RF", "GBM"), "Accuracy" = c(cm_rpart$overall[1], cmRF$overall[1], cmGBM$overall[1]), "Out of Sample Error" = c(1 -  cm_rpart$overall[1], 1 - cmRF$overall[1], 1 -  cmGBM$overall[1]))
AccuracyResults
```

```
##         Model  Accuracy Out.of.Sample.Error
## 1 Tree(rpart) 0.5413764         0.458623619
## 2          RF 0.9959218         0.004078165
## 3         GBM 0.9923534         0.007646559
```

#Predictions on (Validation) Test Data

The next possible step might be using the ensembling methods in learning, to combine classifiers by averaging or voting to improve accuracy in the model.  However, given the high accuracy of two models (Random Forests and Generalized Boosting Models) above, and the interpretability reductions and computational complexity increase of the ensembling methods, we will skip these further research efforts for now.
We will use the Random Forests Model that has the highest accuracy as our prediction model to predict the classe for the given 20 different test cases on the original test data. 


```r
pred <- predict(rfModFit, newdata = testData)
pred
```

```
##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E
```

#Conclusions
Based on our analysis above on the prediction model building and selection of the 3 models, i.e. decision trees, random forests, and generalized gradient boosting models, we concluded that the random forests model (with cross validation) with the highest accucracy of 0.9959 and the expected out of sample error of 0.004078 is the best predictive model to use to predict the test cases.    

The outcome of the 20 test cases prediction is listed as below:

```r
testDataPredResults <- data.frame ("problem_id" = testData$problem_id, "predicted_classe" = pred)
testDataPredResults
```

```
##    problem_id predicted_classe
## 1           1                B
## 2           2                A
## 3           3                B
## 4           4                A
## 5           5                A
## 6           6                E
## 7           7                D
## 8           8                B
## 9           9                A
## 10         10                A
## 11         11                B
## 12         12                C
## 13         13                B
## 14         14                A
## 15         15                E
## 16         16                E
## 17         17                A
## 18         18                B
## 19         19                B
## 20         20                B
```
